--------------------------------------------------------
--  파일이 생성됨 - 금요일-9월-01-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table INVITE_CARD
--------------------------------------------------------

  CREATE TABLE "PARTY"."INVITE_CARD" 
   (	"SEQUENCEID" NUMBER, 
	"CLIENT_ID" VARCHAR2(128 BYTE), 
	"PLACE_ID1" NUMBER, 
	"PLACE_ID2" NUMBER, 
	"PLACE_ID3" NUMBER, 
	"TITLE" VARCHAR2(256 BYTE), 
	"TARGET_DATE" VARCHAR2(128 BYTE), 
	"TARGET_TIME" VARCHAR2(128 BYTE), 
	"MEETING_CONTENT" VARCHAR2(2056 BYTE), 
	"MEETING_PARTICIPANTS" VARCHAR2(128 BYTE), 
	"CARD_SKIN" VARCHAR2(28 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PARTY.INVITE_CARD
SET DEFINE OFF;
Insert into PARTY.INVITE_CARD (SEQUENCEID,CLIENT_ID,PLACE_ID1,PLACE_ID2,PLACE_ID3,TITLE,TARGET_DATE,TARGET_TIME,MEETING_CONTENT,MEETING_PARTICIPANTS,CARD_SKIN) values (2,'party',273,434,774,'자연/공원/드림파크 야생화공원','2023-08-28','23:37','12','12',null);
Insert into PARTY.INVITE_CARD (SEQUENCEID,CLIENT_ID,PLACE_ID1,PLACE_ID2,PLACE_ID3,TITLE,TARGET_DATE,TARGET_TIME,MEETING_CONTENT,MEETING_PARTICIPANTS,CARD_SKIN) values (3,'party',382,417,784,'자연/자연경관/승봉도 연꽃단지','2023-08-28','23:43','저장 완료 성공인가!','5명',null);
Insert into PARTY.INVITE_CARD (SEQUENCEID,CLIENT_ID,PLACE_ID1,PLACE_ID2,PLACE_ID3,TITLE,TARGET_DATE,TARGET_TIME,MEETING_CONTENT,MEETING_PARTICIPANTS,CARD_SKIN) values (4,'tester',378,579,766,'자연/기타/볼음도 저어새 도래지','2023-08-29','02:13',null,null,null);
Insert into PARTY.INVITE_CARD (SEQUENCEID,CLIENT_ID,PLACE_ID1,PLACE_ID2,PLACE_ID3,TITLE,TARGET_DATE,TARGET_TIME,MEETING_CONTENT,MEETING_PARTICIPANTS,CARD_SKIN) values (5,'party',95,415,757,'관광/기타/인천역','2023-08-29','03:17','페이징처리 테스트','6명',null);
Insert into PARTY.INVITE_CARD (SEQUENCEID,CLIENT_ID,PLACE_ID1,PLACE_ID2,PLACE_ID3,TITLE,TARGET_DATE,TARGET_TIME,MEETING_CONTENT,MEETING_PARTICIPANTS,CARD_SKIN) values (6,'party',226,490,844,'전시/박물관/기념관/인천어린이박물관','2023-08-29','03:18','1','1',null);
Insert into PARTY.INVITE_CARD (SEQUENCEID,CLIENT_ID,PLACE_ID1,PLACE_ID2,PLACE_ID3,TITLE,TARGET_DATE,TARGET_TIME,MEETING_CONTENT,MEETING_PARTICIPANTS,CARD_SKIN) values (7,'party',232,555,603,'전시/박물관/기념관/애보박물관','2023-08-29','03:18','1','1',null);
Insert into PARTY.INVITE_CARD (SEQUENCEID,CLIENT_ID,PLACE_ID1,PLACE_ID2,PLACE_ID3,TITLE,TARGET_DATE,TARGET_TIME,MEETING_CONTENT,MEETING_PARTICIPANTS,CARD_SKIN) values (8,'party',191,500,661,'전시/박물관/기념관/범패민속문화박물관','2023-08-29','03:18',null,null,null);
Insert into PARTY.INVITE_CARD (SEQUENCEID,CLIENT_ID,PLACE_ID1,PLACE_ID2,PLACE_ID3,TITLE,TARGET_DATE,TARGET_TIME,MEETING_CONTENT,MEETING_PARTICIPANTS,CARD_SKIN) values (9,'party',142,475,708,'관광/휴양관광/약석원','2023-08-29','03:19',null,null,null);
Insert into PARTY.INVITE_CARD (SEQUENCEID,CLIENT_ID,PLACE_ID1,PLACE_ID2,PLACE_ID3,TITLE,TARGET_DATE,TARGET_TIME,MEETING_CONTENT,MEETING_PARTICIPANTS,CARD_SKIN) values (10,'party',55,459,648,'관광/기타/대청도 광난두정자각','2023-08-29','03:19','가장 마지막에 저장한 카드가 1번으로 올라옵니다','1명',null);
Insert into PARTY.INVITE_CARD (SEQUENCEID,CLIENT_ID,PLACE_ID1,PLACE_ID2,PLACE_ID3,TITLE,TARGET_DATE,TARGET_TIME,MEETING_CONTENT,MEETING_PARTICIPANTS,CARD_SKIN) values (21,'tester',213,419,662,'전시/박물관/기념관/토지금고 마을박물관','2023-08-30','09:45',null,null,null);
Insert into PARTY.INVITE_CARD (SEQUENCEID,CLIENT_ID,PLACE_ID1,PLACE_ID2,PLACE_ID3,TITLE,TARGET_DATE,TARGET_TIME,MEETING_CONTENT,MEETING_PARTICIPANTS,CARD_SKIN) values (22,'tester',330,578,804,'자연/자연경관/대이작도 오형제바위','2023-08-30','11:45','^^^',null,null);
Insert into PARTY.INVITE_CARD (SEQUENCEID,CLIENT_ID,PLACE_ID1,PLACE_ID2,PLACE_ID3,TITLE,TARGET_DATE,TARGET_TIME,MEETING_CONTENT,MEETING_PARTICIPANTS,CARD_SKIN) values (23,'tester',295,523,862,'자연/섬/바다/연평도 구리동해변~~~','2023-08-30','15:24',null,null,null);
--------------------------------------------------------
--  DDL for Index SYS_C007590
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARTY"."SYS_C007590" ON "PARTY"."INVITE_CARD" ("SEQUENCEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table INVITE_CARD
--------------------------------------------------------

  ALTER TABLE "PARTY"."INVITE_CARD" ADD PRIMARY KEY ("SEQUENCEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
